namespace: kcp-glbc

resources:
  - ../../../config/default
  - service.yaml

patches:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kcp-glbc-controller-manager
    spec:
      template:
        spec:
          containers:
            - name: manager
              # Force glbc-controller to use the local image
              imagePullPolicy: Never
              ports:
              # add the transform endpoint port
              - containerPort: 8090
                name: transform
                protocol: TCP

configMapGenerator:
- name: controller-config
  behavior: merge
  literals:
  - GLBC_TLS_PROVIDER=glbc-ca
  - GLBC_ARGOCD_PLUGIN="true"