resources:
  - ../../kube-prometheus
  - ingress-prometheus.yaml
  - ingress-grafana.yaml
  - monitoring_resources/dashboard_glbc.yaml

# Patch grafana deployment to include dashboard configmaps
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    path: grafana_patch.yaml
