apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-glbc-application
spec:
  destination:
    name: in-cluster
    namespace: example-glbc-application
  project: default
  source:
    # TODO: Change this to glbc repo when manifests folder changes land there
    repoURL: https://github.com/roivaz/kcp-glbc.git
    targetRevision: argocd-glbc-plugin
    path: argocd-glbc-plugin/manifests/test-app
    plugin: {}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true