{
 "title": "GLBC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "AWS Route53 Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glbc_aws_route53_request_total[$__range]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(increase(glbc_aws_route53_request_errors_total[$__range]))",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "TLS Cert Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{result=\"failed\"}[$__range])) by (issuer)",
     "legendFormat": "Total {{issuer}}"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{result=\"succeeded\"}[$__range])) by(issuer)",
     "legendFormat": "Total Succeeded {{issuer}}"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{result=\"failed\"}[$__range])) by (issuer)",
     "legendFormat": "Total Failed {{issuer}}"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_secret_count{}[$__range])) by (issuer)",
     "legendFormat": "Total Secrets {{issuer}}"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_pending_request_count{}[$__range])) by (issuer)",
     "legendFormat": "Total Pending {{issuer}}"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_issuance_duration_seconds_bucket{issuer=\"letsencryptprod\"}[1h])) by (issuer) - sum(increase(glbc_tls_certificate_issuance_duration_seconds_bucket{issuer=\"letsencryptprod\", le=\"300\"}[1h])) by (issuer)",
     "legendFormat": "Total > 5mins {{issuer}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Limits"
    },
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"manager\"}  ",
     "legendFormat": "Container Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Limits"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "CPU Load {{pod}}"
    }
   ]
  }
 ]
}